version: '3.8'
services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8080:8080"
  zoo1:
    image: confluentinc/cp-zookeeper:7.0.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    env_file:
      - .env
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log

  kafka1:
    image: confluentinc/cp-kafka:7.0.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "9999:9999"
    env_file:
      - .env
    depends_on:
      - zoo1
    volumes:
      - kafka_data:/var/lib/kafka/data
volumes:
  data:
  kafka_data:
  zookeeper_data:
  zookeeper_logs:
